// SPDX-FileCopyrightText: rust-yaml contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

import { createReadStream, existsSync, statSync } from "node:fs";
import { extname, join, resolve, sep } from "node:path";

import type { Plugin } from "vite";

// rustdoc is generated by cargo into target/doc, which lives outside srcDir and
// is therefore invisible to VitePress. `.github/scripts/create-docs-pages.sh`
// grafts it onto the bundle at /api/ only when assembling for deployment, so
// without this middleware the API nav entry and hero button 404 under
// `bun run dev` -- broken in exactly the environment the docs are written in.
//
// `apply: "serve"` is load-bearing: the production bundle must keep coming from
// the deploy script, which is what CI runs. If this plugin also applied at build
// time it would copy 10 MB of rustdoc into .vitepress/dist and give two
// different code paths for producing the same directory.

const CONTENT_TYPES: Record<string, string> = {
  ".css": "text/css; charset=utf-8",
  ".html": "text/html; charset=utf-8",
  ".js": "text/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".txt": "text/plain; charset=utf-8",
  ".woff2": "font/woff2",
};

/**
 * Serve `docDir` at `<base>api/` for the dev server only.
 *
 * @param base    VitePress `base`, with both leading and trailing slash.
 * @param docDir  Absolute path to cargo's `target/doc`.
 */
export function rustdocDev(base: string, docDir: string): Plugin {
  const prefix = `${base}api/`;
  const root = resolve(docDir);

  return {
    name: "rust-yaml:rustdoc-dev",
    apply: "serve",

    configureServer(server): void {
      server.middlewares.use((req, res, next): void => {
        const url = req.url ?? "";
        // `${base}api` with no trailing slash would otherwise fall through to
        // VitePress and render its 404.
        if (url === `${base}api`) {
          res.statusCode = 301;
          res.setHeader("Location", prefix);
          res.end();
          return;
        }
        if (!url.startsWith(prefix)) {
          next();
          return;
        }

        if (!existsSync(root)) {
          // A 404 here is indistinguishable from a broken link, so say what is
          // actually missing and how to produce it.
          res.statusCode = 503;
          res.setHeader("content-type", "text/html; charset=utf-8");
          res.end(
            `<h1>rustdoc not built</h1><p>Run <code>cargo doc --all-features --no-deps</code> ` +
              `to populate <code>${root}</code>, then reload. ` +
              `The deployed site builds it via <code>mise run docs:pages</code>.</p>`,
          );
          return;
        }

        // `?? ""` satisfies noUncheckedIndexedAccess: split always yields at
        // least one element, but the compiler cannot know that.
        const rel = decodeURIComponent(
          url.slice(prefix.length).split(/[?#]/)[0] ?? "",
        );
        let file = resolve(join(root, rel));

        // Path traversal guard. `rel` comes straight off the request line, and
        // `..` segments would otherwise escape target/doc and serve any file the
        // dev server can read. Compare against `root + sep` so a sibling
        // directory sharing the prefix (target/doc-old) cannot match either.
        if (file !== root && !file.startsWith(root + sep)) {
          res.statusCode = 403;
          res.end("forbidden");
          return;
        }

        // Redirect rather than serve the crate index inline. This mirrors the
        // api/index.html that create-docs-pages.sh writes, and it is load
        // bearing: rustdoc's index.html references its assets relatively
        // (`../static.files/main-*.js`). Served at /api/ those resolve to
        // /rust-yaml/static.files/, one level too high and outside this
        // prefix, so they fall through to VitePress and every script tag
        // receives the SPA HTML shell -- "Unexpected token '<'" in the console.
        if (rel === "" || rel === "/") {
          res.statusCode = 302;
          res.setHeader("Location", `${prefix}rust_yaml/index.html`);
          res.end();
          return;
        }
        if (existsSync(file) && statSync(file).isDirectory())
          file = join(file, "index.html");

        if (!existsSync(file)) {
          next();
          return;
        }

        res.setHeader(
          "content-type",
          CONTENT_TYPES[extname(file)] ?? "application/octet-stream",
        );
        createReadStream(file).pipe(res);
      });
    },
  };
}
